CSC/CSC/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name="core"),
    path('eventos/', include('event.urls', namespace="events")),
    path('usuarios/', include('account.urls', namespace="users")),
]


if settings.DEBUG:
   from django.conf.urls.static import static
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
#    import debug_toolbar
#    from django.urls import include
#    urlpatterns = [
#        path('__debug__/', include(debug_toolbar.urls))
#    ] + urlpatterns

CSC/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
    path('registro/', views.register_user, name="register"),
    path('identificar/',
         auth_views.LoginView.as_view(template_name="account/login.html"),
         name="login"),
    path('salir/',
         auth_views.LogoutView.as_view(), name="logout")
]

CSC/core/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('eventos/', include('event.urls', namespace="events")),
]

CSC/event/urls.py
from django.urls import path
from .views import EventListView, event_detail

app_name = 'events'

urlpatterns = [
    path('', EventListView.as_view(), name="list"),
    path('<slug:slug>', event_detail, name="detail")
]

CSC/core/models.py
from django.db import models


class Contact(models.Model):
    name    = models.CharField(max_length=40, verbose_name="nombre")
    email   = models.EmailField(max_length=100, )
    phone   = models.CharField(max_length=10, verbose_name="telefono")
    message = models.TextField(verbose_name="mensaje")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} - {self.phone}'

    
    class Meta:
        ordering = ['-created']
        verbose_name = 'contacto'
 

CSC/core/forms.py
from django import forms
from django.forms import ValidationError
from material import Layout
from .models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        exclude = ('created',)

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        
        if not phone.isdigit():
            raise ValidationError("El telefono debe ser únicamente numerico")

        return phone

    layout = Layout('name', 'email', 'phone', 'message')

CSC/core/views.py
from django.conf import settings
from django.core.mail import EmailMessage, send_mail
from django.shortcuts import render, redirect
from django.urls import reverse

from event.models import Gallery
from .forms import ContactForm
from .models import Contact


def index(request):
    gallery = Gallery.objects.filter(name__exact="eventos en general").values(
                                                   'photo1', 'photo2', 'photo3',
                                                   'photo4', 'photo5', 'photo6',
                                                   'photo7', 'photo8', 'photo9',
                                                   'photo10', 'photo11', 'photo12')
    
    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            name = request.POST.get('name')
            email = request.POST.get('email')
            phone = request.POST['phone']
            message = request.POST.get('message')

            sendMail = EmailMessage(
                'CSC: Nuevo mensaje de contacto',
                f'De: {name} <{email}>\nTelefono:{phone}\n\nMensaje:\n{message}',
                email,
                ['nfraire07@csc-its.com'],
                reply_to=[email]
            )

            try:
                sendMail.send()
                c = Contact(name=name, email=email, phone=phone, message=message)
                c.save()

                return redirect(reverse('index')+'?ok&#main-header')
            except:
                return redirect(reverse('index')+'?error&#contact-form')
    else:
        contact_form = ContactForm()
    
    return render(request, 'core/index.html', {'form': contact_form, 'gallery': gallery})

CSC/core/templates/core/_alerts.html
{% if messages %}
{% comment %} {{ messages }} {% endcomment %}
    {% comment %} {% for message in messages %} {% endcomment %}
        <p class="alert-custom center z-depth-1
            {% if message.tags == success %} teal lighten-4
            {% elif message.tags == error %} red lighten-3
            {% endif %}">

            {% for message in messages %}
                {{ message }}
            {% endfor %}

            {% if message.tags == success %} 
                <i class="material-icons">check_circle</i>    
            {% elif message.tags == error %}
                <i class="material-icons">error_outline</i>
            {% endif %}
        </p>
    {% comment %} {% endfor %} {% endcomment %}
{% endif %}

CSC/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    {% block gtag %}{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% include 'material/includes/material_css.html' %}
    <link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Saira+Semi+Condensed&display=swap" rel="stylesheet">

    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}" media="screen">
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>    
    {% if request.path == '/' %}
        <div id="particles-js"></div>
        <header class="main-header grey lighten-3" id="main-header">
    {% else %}
        <div id="particles-js2"></div>
        <header class="secondary-header grey lighten-3">
    {% endif %}
        <nav class="transparent z-depth-0">
            <div class="container">
                <div class="nav-wrapper">
                    <a href="{% url 'index' %}" class="brand-logo hide-on-med-and-down"><h4>CSC</h4></a>
                     <a href="#" data-target="mobile-nav" class="sidenav-trigger">
                        <i class="fas fa-bars fa-2x"></i>
                    </a>
                    <ul class="right hide-on-med-and-down">
                         <li>
                            <a href="{% url 'index' %}"
                               class="{% if request.path == '/' %} active-link {% endif %}">
                                Inicio
                            </a>
                        </li>
                         <li>
                            <a href="{% url 'events:list' %}" class="{% if request.path == '/eventos/' %} active-link {% endif %}">
                                Eventos
                            </a>
                        </li>
                        {% comment %} 
                        <li><a href="blog.html">Blog</a></li> {% endcomment %}
                        {% if not request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'account:login' %}"
                                class="{% if request.path == '/usuarios/identificar/' %} active-link {% endif %}">
                                    Iniciar sesión 
                                </a>
                            <li>
                                <a href="{% url 'account:register' %}"
                                class="{% if request.path == '/usuarios/registro/' %} active-link {% endif %}">
                                    Registrate
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a class="dropdown-trigger" href="#!" data-target="drop-account">
                                    Mi cuenta<i class="material-icons right">arrow_drop_down</i>
                                </a>
                            </li>
                            <ul id="drop-account" class="dropdown-content">
                                <li class="divider"></li>
                                <li>
                                    <a href="{% url 'account:logout' %}">
                                        Salir
                                    </a>
                                </li>
                            </ul>

                        {% endif %}
                    </ul>
                     <ul class="sidenav" id="mobile-nav">
                        <h3 class="center">CSC</h3>
                        <li><div class="divider"></div></li>
                        <li><a href="{% url 'index' %}">Inicio <i class="fas fa-home left"></i></a></li>
                        <li><a href="{% url 'events:list' %}">Eventos <i class="fas fa-calendar-day left"></i></a></li>
                        {% comment %} <li><a href="blog.html">Blog <i class="fas fa-blog left"></i></a></li> {% endcomment %}
                        <li><div class="divider"></div></li>
                        {% if not request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'account:login' %}">
                                    Iniciar sesión <i class="fas fa-sign-in-alt left"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'account:register' %}">
                                    Registrate <i class="fas fa-user-plus left"></i>
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'account:logout' %}">
                                    Salir <i class="fas fa-sign-out-alt"></i>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="showcase container">
            <div class="row center">
                <div class="col s10 offset-s1">
                    <img src="{% static 'img/logo.png' %}" 
                            width="{% if request.path == '/' %} 470px {% else %} 370px {% endif %}"
                            class="responsive-img" alt="capitulo de sistemas computacionales">
                    {% block showcase %}{% endblock showcase %}
                </div>
            </div>
        </div>
    </header>

    {% block content %}{% endblock content %}

    <footer class="section white-text center">
        <a href="https://www.facebook.com/CapituloEstudiantilDeSistemasComputacionales/"
           target="_blank">
            <i class="fab fa-facebook fa-3x"></i>
        </a>
        <a href="https://www.instagram.com/cscits/" target="_blank">
            <i class="fab fa-instagram fa-3x"></i>
        </a>
        <p>Capítulo de sistemas computacionales &copy; 2020</p>
    </footer>

    <script src="https://kit.fontawesome.com/e8273593cf.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/particles.min.js' %}"></script>

    {% include 'material/includes/material_js.html' %}

    {% if request.path == '/' %}
        <script src="{% static 'js/particulas.js' %}"></script>
    {% else %}
        <script src="{% static 'js/particulas2.js' %}"></script>
    {% endif %}
    
    <script type="text/javascript">
    
        document.addEventListener('DOMContentLoaded', function() {
            var sideNav = document.querySelectorAll('.sidenav ');
            var initSideNav = M.Sidenav.init(sideNav);

            var boxed = document.querySelectorAll('.materialboxed');
            var initBoxed = M.Materialbox.init(boxed);

            var dropdown = document.querySelectorAll('.dropdown-trigger');
            var initDropdown = M.Dropdown.init(dropdown);

            var carousel = document.querySelectorAll('.carousel');
            var initCarousel = M.Carousel.init(carousel)
        });

        console.log("%cDesarrollado por:", "color:#85e085;")

        console.log(
        "%c                         \n" +
        "  ███╗   ██╗██╗████████╗ █████╗ ██╗ \n" +
        "  ████╗  ██║██║╚══██╔══╝██╔══██╗██║ \n" +
        "  ██╔██╗ ██║██║   ██║   ███████║██║ \n" +
        "  ██║╚██╗██║██║   ██║   ██╔══██║██║ \n" +
        "  ██║ ╚████║██║   ██║   ██║  ██║██║ \n" +
        "  ╚═╝  ╚═══╝╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝ \n", "color:#85cc95;font-size:15px");


        console.log("%c¿Te gustaría colaborar con el proyecto?", "color:#85e085");
        console.log("%cEscríbeme a: %cnfraire07@csc-its.com","color:#85e085","text-decoration:underline #ff6666;color:#ff6666");
    </script>
</body>
</html>

CSC/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block gtag %}
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-157747004-1"></script>
	<script>
 		 window.dataLayer = window.dataLayer || [];
		 function gtag(){dataLayer.push(arguments);}
	 	 gtag('js', new Date());

		 gtag('config', 'UA-157747004-1');
	</script>	
{% endblock gtag %}

{% block title %} Inicio {% endblock title %}

{% block showcase %}
    <h2>Bienvenido</h2>
{% endblock %}

{% block content %}
<section class="section values-section center">
    <div class="container">
        <div class="row">
            <div class="col s12 l4">
                <div class="card-panel z-depth-3">
                    <img src="{% static 'img/cogwheel.png' %}" height="75px">
                    <h5>Compromiso</h5>
                    <p>
                        Organización de actividades favorables para los estudiantes de la carrera para incentivar,
                        motivar y completar su formación como estudiante integral. 
                    </p>
                </div>
            </div>
            <div class="col s12 l4">
                <div class="card-panel z-depth-3">
                    <img src="{% static 'img/respect.png' %}" height="75px">
                    <h5>Respeto</h5>
                    <p>
                        Conocer el valor propio y honrar el valor de los demás es la verdadera manera de ganar respeto.
                        Se reconoce el valor de la sociedad estudiantil.
                    </p>
                </div>
            </div>
            <div class="col s12 l4">
                <div class="card-panel z-depth-3">
                    <img src="{% static 'img/goal.png' %}" height="75px">
                    <h5>Responsabilidad</h5>
                    <p>
                        Virtud de no solo tomar desiciones de manera consciente sino también de asumir las consecuencias
                        que tengan siempre con actitud de crecimiento.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section who-we-are-section">
    <div class="container">
        <div class="row">
            <div class="col s12 l5">
                <img src="{% static 'img/cscteam.jpeg' %}" class="responsive-img z-depth-2">
            </div>
            <div class="col s12 l6 side-points">
                <h4>Nuestro enfoque</h4>
                <div class="row">
                    <div class="col s12 m6">
                        <i class="fas fa-tachometer-alt fa-2x"></i>
                        <h5>Eficacia</h5>
                        <p>Se ponen en acción inquietudes y ser un agente de cambio, poner en práctica y desarrollar diferentes habilidades para la adquisición de experiencia.</p>
                    </div>
                    <div class="col s12 m6">
                        <i class="fas fa-users fa-2x"></i>
                        <h5>Comunidad</h5>
                        <p>Desarrollar el sentido de la participación social, para mejorar la calidad de trabajo en nuestra comunidad y el país.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m6">
                        <i class="fas fa-laptop-code fa-2x"></i>
                        <h5>Ideas creativas</h5>
                        <p>Atender, canalizar, dar seguimiento y solucionar de forma satisfactoria las necesidades de los estudiantes.</p>
                    </div>
                    <div class="col s12 m6">
                        <i class="fas fa-puzzle-piece fa-2x"></i>
                        <h5>Somos un equipo</h5>
                        <p>Formado por estudiantes que se identifican por un mismo interés y comparten un objetivo en común.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'event/_gallery.html' %}

<section class="section partners-section grey lighten-3 center">
    <div class="contaier">
        <div class="row">
            <div class="col s12 m3">
                <img src="{% static 'img/hexa2.png' %}" alt="">
            </div>
            <div class="col s12 m3">
                <img src="{% static 'img/clicvk.png' %}" alt="">
            </div>
            <div class="col s12 m3">
                <img src="{% static 'img/justia2.png' %}" alt="">
            </div>
            <div class="col s12 m3">
                <img src="{% static 'img/txm2.png' %}" alt="">
            </div>
            <!-- <div class="col s12 m2">
                <img src="{% static 'img/justia.png' %}" alt="">
            </div> -->
        </div>
    </div>
</section>

<section class="section contact-section">
    <div class="container">
        <div class="row">
            <div class="col sm12 m6 contact-info">
                <h3>Contactanos</h3> 
                <p>
                    Te gustaría formar parte del capítulo de sistemas, tienes algúna duda, comentario y/o sugerencia acerca de nostros.<br>
                    Escríbenos! te atenderemos lo antes posible.
                </p>
                <p>
                    <i class="fas fa-map-marker-alt fa-2x"></i>
                    <span>
                        Blvd. Venustiano Carranza #2400 <br> Colonia Tecnológico
                        Saltillo, Coahuila, México C.P 25280.
                    </span>
                    <br>
                    <br>
                    <i class="fas fa-clock fa-2x"></i>
                    <span>
                        Lunes a viernes: 7:00 a.m a 08:00 p.m
                    </span>
                    <br>
                    <br>
                    {% comment %} <i class="fas fa-phone-alt prefix fa-2x "></i>
                    <span>
                        (844) 123-53-44
                    </span> {% endcomment %}
                </p>
            </div>
            <div class="col sm 12 m6">
                <div class="card-panel grey lighten-4 grey-text text-darken-4" id="contact-form">
                {% if 'ok' in request.GET %}
                    <span class="alert-success-contact">
                    </span>
                {% elif 'error' in request.GET %}
                    <span class="alert-error-contact">
                        {% comment %} No se pudo enviar tu mensaje, intentalo de nuevo. {% endcomment %}
                    </span>
                {% endif %}
                    {% load material_form %}
                    <form method="POST">
                        {% csrf_token %}
                        {% form %}
                            {% part form.name prefix %} <i class="material-icons prefix">account_circle</i> {% endpart %}
                            {% part form.email prefix %} <i class="fas fa-at prefix"></i> {% endpart %}
                            {% part form.phone prefix %} <i class="fas fa-phone-alt prefix"></i> {% endpart %}
                            {% part form.message prefix %} <i class="fas fa-comment-dots prefix"></i> {% endpart %}
                        {% endform %}
                        <button type="submit" class="btn">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}